"""Configuration for cross-merchant credit scoring"""

from scoring.merchant.config import (
    TINYBIRD_HOST,
    TINYBIRD_TOKEN,
    WEIGHT_RELIABILITY,
    WEIGHT_INTENT,
    WEIGHT_TIMELINESS,
    WEIGHT_CAPACITY,
    TENURE_MULTIPLIER,
    HIGH_RISK_FAILURES,
    MEDIUM_RISK_FAILURES,
    LOW_RISK_FAILURES,
    PENALTY_HIGH_RISK,
    PENALTY_MEDIUM_RISK,
    PENALTY_LOW_RISK,
    PENALTY_INSUFFICIENT_FUNDS_THRESHOLD,
    PENALTY_INSUFFICIENT_FUNDS_SEVERE,
    MIN_PAID_INVOICES,
    MIN_TENURE_DAYS,
    TIER_THRESHOLDS,
    CREDIT_MULTIPLIERS,
    INTEREST_RATES,
    EXPECTED_DEFAULT_RATES,
)

MERCHANT_DIVERSITY_BONUS = 10   # +10 points per additional merchant beyond first
MAX_DIVERSITY_BONUS = 30        # Cap at 3 extra merchants
